[package]
name = "mommy_suite"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "mommy_lib",
    "mommy_lang",
    "mommy_shell",
]
resolver = "2"

[dependencies]
mommy_lib = { path = "mommy_lib" }
