[package]
name = "mommy_suite"
version = "0.9.3"
edition = "2021"

[workspace]
members = [
    "mommy_lib",
    "mommy_lang",
    "mommy_shell",
    "mommy_installer",
]
resolver = "2"

[dependencies]
mommy_lib = { path = "mommy_lib" }
